[package]
name = "tfhe-rs-linreg"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.7.2", features = [ "boolean", "shortint", "integer", "x86_64-unix" ] }
rand = { version = "0.8.0", features = [ "getrandom" ] }
rand_chacha = "0.3.1"
rstats = "2.1.12"